name: Run static 

jobs:
  static_analysis_dev:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/static_analysis.yml@master
    secrets: inherit
    with:
      branch: ms_dev
      actions_branch: master
